# Generated by Django 4.1 on 2022-10-24 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='Ваше Ф.И.О.')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Допускаются только цифры', regex='^\\+?1?\\d{9,15}$'), django.core.validators.MaxLengthValidator], verbose_name='Ваш номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('message', models.TextField(verbose_name='Комментарий к заявке')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Обработано')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_order', to='tour.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-pk'],
            },
        ),
    ]
