# Generated by Django 4.1 on 2022-08-30 10:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/%Y/%m/%d', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Стоимость')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('in_two_rows', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
