# Generated by Django 4.1 on 2022-09-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_remove_service_in_two_rows_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=500, verbose_name='Позиция'),
        ),
    ]
