# Generated by Django 4.1 on 2022-09-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_category_options_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
