# Generated by Django 4.1 on 2022-08-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('url', models.CharField(help_text='URL или URI для страницы, например /about/ или http://a-tour.ru/', max_length=256, verbose_name='URL адрес')),
                ('target', models.CharField(blank=True, choices=[('_blank', '_blank'), ('_top', '_top'), ('_parent', '_parent')], max_length=10, null=True, verbose_name='Метод')),
                ('position', models.IntegerField(default=500, verbose_name='Позиция')),
                ('authorized_only', models.BooleanField(blank=True, default=False, help_text='Если установить, то пункт меню будет показан только для авторизированных пользователей', verbose_name='Для авторизированных')),
                ('anonymous_only', models.BooleanField(blank=True, default=False, help_text='Если установить, то пункт меню будет показан только для не авторизированных пользователей', verbose_name='Для анонимных')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu_item', to='menu.menu', verbose_name='ID меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
