# Generated by Django 4.1 on 2022-10-20 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_body_alter_page_datetime_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='Ваше Ф.И.О.')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Допускаются только цифры', regex='^\\+?1?\\d{9,15}$'), django.core.validators.MaxLengthValidator], verbose_name='Ваш номер телефона')),
                ('message', models.TextField(verbose_name='Комментарий к заявке')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звоноки',
                'ordering': ['-pk'],
            },
        ),
    ]
