# Generated by Django 4.1 on 2022-10-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_сallback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сallback',
            new_name='Callback',
        ),
    ]
