# Generated by Django 4.1 on 2022-10-20 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_сallback_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='datetile_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='callback',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 20, 3, 59, 32, 431410, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callback',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
