# Generated by Django 4.1 on 2022-10-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_callback_datetile_update_callback_datetime_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='datetile_update',
            new_name='datetime_update',
        ),
    ]
