# Generated by Django 4.1 on 2022-10-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-pk'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Выберите рейтинг'), (1, 'Одна звезда'), (2, 'Две звезды'), (3, 'Три звезды'), (4, 'Четыре звезды'), (5, 'Пять звезд')], verbose_name='Рейтинг'),
        ),
    ]
